package com.aura.service.service;

import org.springframework.stereotype.Service;

@Service
public class MockLLMService implements LLMService {
    
    @Override
    public String generateReply(String prompt) {
        return "This is a mock LLM-generated reply. In production, this would be generated by an actual LLM based on the prompt: " + prompt;
    }
    
    @Override
    public String generateCrisisPlan(String prompt) {
        return "Mock Crisis Management Plan:\n\n" +
               "1. Immediate Response: Issue a public statement acknowledging the situation.\n" +
               "2. Assessment: Gather all facts and assess the severity of the crisis.\n" +
               "3. Communication Strategy: Develop key messages for different stakeholders.\n" +
               "4. Action Plan: Implement corrective measures and monitor progress.\n" +
               "5. Follow-up: Continue monitoring sentiment and adjust strategy as needed.\n\n" +
               "This is a mock plan. In production, this would be generated by an actual LLM based on: " + prompt;
    }
}
